class ProjectEuler2 {
	public static void main(String[] args) {
		
		// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

		// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	
		int sum = 0;
		int i = 1;
		while (F(i) < 4000000) {
			if (F(i) % 2 == 0) {
				sum += F(i);
			}
			i++;
		}
		
		System.out.println(sum);
	}
	
	static public int F (int n) {
		if (n == 1) return 1;
		else if (n == 2) return 2;
		else return F(n - 1) + F(n - 2);
	}
	
}